### ISSUE TITLE
Onde inserir a chave de Produção ou Homologação?

### ISSUE THREAD

**Issue by ThiagoSantos01** [mferracioli/magento-clearsale#6]
Desculpa se a pergunta é muito primária, mas não ficou claro pra mim.
Instalei na versão 1.9.1, aparentemente está ok, porém sem a inserção desses dados fica com a mensagem de ERRO NA INTEGRAÇÃO.

abs!

**Comment by lucasguarni** [comment]
Olá, vamos ver se consigo te ajudar =p.
Para inserir a chave de produção/homologação, você deve ir em:
Sistema > Configuração > Serviços de Pagamento. 
Ou se tiver em inglês
System > Configuration > Payment Services.

Segue uma imagem de exemplo:
![clearsale](https://cloud.githubusercontent.com/assets/5614013/15197418/bed75810-17a7-11e6-971f-bbcaa64c6129.jpg)

**Comment by ThiagoSantos01** [comment]
Valeu @LucasGuarnieri, é exatamente isso!
